# Generated by Django 5.1.1 on 2024-12-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
