# Generated by Django 5.1.1 on 2024-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_qr_code_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='feedback_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
