# Generated by Django 5.1.1 on 2024-11-24 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_average_rating_lesson_feedback_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='rating',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг предмета'),
        ),
    ]
