# Generated by Django 5.1.1 on 2024-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='average_rating',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
