# Generated by Django 5.1.1 on 2024-11-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='activation_duration',
        ),
    ]
