# Generated by Django 5.1.1 on 2024-11-28 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_lesson_activation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='activation_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
    ]
