# Generated by Django 5.1.1 on 2024-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_lesson_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='average_rating',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
