# Generated by Django 5.1.1 on 2024-11-28 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='rating',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='average_rating',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг предмета'),
        ),
    ]
